#ifndef MTFS_RA8P1_ETHOSU_INSTANCE_H
#define MTFS_RA8P1_ETHOSU_INSTANCE_H

#include "ethosu_driver.h"
#include "rm_ethosu.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Generated by FSP in ra_gen/common_data.c.  Keep C++ providers independent
 * of common_data.h because enabling RSIP adds private headers that do not have
 * a consistent C++ linkage contract. */
extern struct ethosu_driver g_ethosu0;
extern rm_ethosu_instance_ctrl_t g_rm_ethosu0_ctrl;
extern const rm_ethosu_cfg_t g_rm_ethosu0_cfg;
extern const rm_ethosu_instance_t g_rm_ethosu0;

#ifdef __cplusplus
}
#endif

#endif
