#include "mtfs_ra8p1_sentinel_npu.h"

#include <stddef.h>

#define RA_PROVIDER MTFS_SENTINEL_PROVIDER_RA_TFLM_ETHOSU
#define RA_ACCELERATOR MTFS_SENTINEL_ACCELERATOR_ETHOS_U55
#define RA_RW (MTFS_SENTINEL_REGION_ACCESS_READ | MTFS_SENTINEL_REGION_ACCESS_WRITE)
#define RA_OWNED (MTFS_SENTINEL_REGION_POLICY_OWNED | \
    MTFS_SENTINEL_REGION_POLICY_EXCLUSIVE | \
    MTFS_SENTINEL_REGION_POLICY_ALLOW_ZEROIZE | \
    MTFS_SENTINEL_REGION_POLICY_GLOBAL_SERIALIZATION)
#define RA_OWNED_CACHE (RA_OWNED | MTFS_SENTINEL_REGION_POLICY_CACHE_MAINTENANCE)
#define RA_PROCESS (MTFS_SENTINEL_REGION_POLICY_EXCLUSIVE | \
    MTFS_SENTINEL_REGION_POLICY_GLOBAL_SERIALIZATION)
#define RA_ZERO_EXCLUSIVE (MTFS_SENTINEL_REGION_REQUIRE_ZEROIZE | \
    MTFS_SENTINEL_REGION_REQUIRE_EXCLUSIVE)

#define CALLER_POLICY(kind_, alignment_, begin_, size_, requirements_, flags_) { \
    RA_PROVIDER, RA_ACCELERATOR, (kind_), \
    MTFS_SENTINEL_PLACEMENT_CALLER_RELATIVE, (alignment_), (begin_), \
    (begin_) + (size_), (size_), RA_RW, RA_RW, (requirements_), (flags_) }

#define PROVIDER_POLICY(kind_, alignment_, size_) { \
    RA_PROVIDER, RA_ACCELERATOR, (kind_), \
    MTFS_SENTINEL_PLACEMENT_PROVIDER_ASSIGNED, (alignment_), 0U, 0U, (size_), \
    RA_RW, RA_RW, MTFS_SENTINEL_REGION_REQUIRE_EXCLUSIVE, RA_PROCESS }

static const mtfs_sentinel_runtime_region_policy_t policies[] = {
    {
        RA_PROVIDER, RA_ACCELERATOR, MTFS_SENTINEL_REGION_RUNTIME_BINARY,
        MTFS_SENTINEL_PLACEMENT_BINARY_CONTAINED, 32U, 0U,
        MTFS_RA8P1_SENTINEL_RUNTIME_BINARY_SIZE,
        MTFS_RA8P1_SENTINEL_RUNTIME_BINARY_SIZE,
        MTFS_SENTINEL_REGION_ACCESS_READ, MTFS_SENTINEL_REGION_ACCESS_READ,
        MTFS_SENTINEL_REGION_REQUIRE_ZEROIZE |
            MTFS_SENTINEL_REGION_REQUIRE_CACHE_COHERENCY,
        MTFS_SENTINEL_REGION_POLICY_OWNED |
            MTFS_SENTINEL_REGION_POLICY_CACHE_MAINTENANCE |
            MTFS_SENTINEL_REGION_POLICY_ALLOW_ZEROIZE
    },
    CALLER_POLICY(MTFS_SENTINEL_REGION_INTERPRETER, 32U, 0U, 224U,
        RA_ZERO_EXCLUSIVE, RA_OWNED),
    CALLER_POLICY(MTFS_SENTINEL_REGION_RESOLVER, 32U, 224U, 64U,
        RA_ZERO_EXCLUSIVE, RA_OWNED),
    CALLER_POLICY(MTFS_SENTINEL_REGION_TENSOR_ARENA, 32U, 288U, 4096U,
        RA_ZERO_EXCLUSIVE | MTFS_SENTINEL_REGION_REQUIRE_CACHE_COHERENCY |
            MTFS_SENTINEL_REGION_REQUIRE_INPUT_OUTPUT_SHARED,
        RA_OWNED_CACHE),
    CALLER_POLICY(MTFS_SENTINEL_REGION_PROVIDER_CONTEXT, 32U, 4384U, 512U,
        RA_ZERO_EXCLUSIVE, RA_OWNED),
    PROVIDER_POLICY(MTFS_SENTINEL_REGION_ACCELERATOR_CONTEXT, 8U, 96U),
    PROVIDER_POLICY(MTFS_SENTINEL_REGION_SEMAPHORE_POOL, 4U, 16U),
    PROVIDER_POLICY(MTFS_SENTINEL_REGION_PROVIDER_SYNC, 4U, 4U)
};

mtfs_error_t mtfs_ra8p1_sentinel_npu_policy(
    const mtfs_sentinel_runtime_region_policy_t **result,
    uint32_t *policy_count)
{
    if (result == NULL || policy_count == NULL) return MTFS_ERROR_INVALID_ARGUMENT;
    *result = policies;
    *policy_count = (uint32_t)(sizeof(policies) / sizeof(policies[0]));
    return MTFS_OK;
}
